[package]
name = "database"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common = { path = "../common" }
chrono = { version = "0.4.44", default-features = false, features = ["std"] }
sqlx = { version = "0.8.6", default-features = false, features = ["chrono", "macros", "postgres", "runtime-tokio-rustls", "uuid"] }
thiserror = "2.0.18"
uuid = { version = "1.22.0", features = ["v4"] }

[dev-dependencies]
testcontainers = "0.28.0"
