from pathlib import Path
from types import TracebackType
from typing import Self

class _NumpyArray:
    @property
    def __array_interface__(self) -> object: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, index: tuple[slice, int]) -> _NumpyArray: ...
    def copy(self) -> _NumpyArray: ...

class SoundFile:
    samplerate: int
    channels: int
    format: str
    subtype: str

    def __init__(self, file: str | Path) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def __len__(self) -> int: ...
    def seek(self, frames: int) -> int: ...
    def read(self, *, frames: int, dtype: str, always_2d: bool) -> _NumpyArray: ...
