[package]
name = "database"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
chrono = { version = "0.4.44", default-features = false, features = ["std"] }
sha2 = "0.10.9"
sqlx = { version = "0.8.6", default-features = false, features = ["chrono", "macros", "migrate", "postgres", "runtime-tokio-rustls"] }
thiserror = "2.0.18"

[dev-dependencies]
testcontainers = "0.28.0"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
