from contextlib import AbstractContextManager
from typing import Final

class Tensor:
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, index: int | tuple[int | slice, ...]) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def mean(self, dim: int, *, keepdim: bool) -> Tensor: ...

bfloat16: Final[object]

def inference_mode() -> AbstractContextManager[None]: ...
