from contextlib import AbstractContextManager
from typing import Final, Protocol

class Tensor:
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, index: int | tuple[int | slice, ...]) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def mean(self, dim: int, *, keepdim: bool) -> Tensor: ...

class _NumpyArray(Protocol):
    @property
    def __array_interface__(self) -> object: ...

bfloat16: Final[object]

def from_numpy(ndarray: _NumpyArray) -> Tensor: ...
def inference_mode() -> AbstractContextManager[None]: ...
